

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs : 
  - job: Job1
    steps:
    - script : echo Job1 Build
    displayName: 'Run a one-line script'

  - job: Job2
    steps :
    - script : echo Job2 Build
    displayName: 'Run a one-line script'

- stage: Test
  jobs : 
  - job: Job1
    steps:
    - script : echo Job1 Test
    displayName: 'Run a one-line script'

  - job: Job
    dependsOn: Job2
    steps:
    - script : echo Job2 test
    displayName: 'Run a one-line script'

- stage: Deploy
  jobs : 
  - job: Job1
    steps:
    - script : echo Job1 Deploy
    displayName: 'Run a one-line script'

   

  

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
